more specific variable names + big histsize

diff --git a/etc/sh/bashrc b/etc/sh/bashrc
--- a/etc/sh/bashrc
+++ b/etc/sh/bashrc
@@ -18,6 +18,7 @@ stty werase undef
 bind '"\C-w": unix-filename-rubout'
 
 # cycle autocomplete
+# @TODO @FIXME: buggy when pasting tabs :(
 bind '"\t":   menu-complete'
 bind '"\e[Z": menu-complete-backward'
 
@@ -26,6 +27,8 @@ bind '"\C-f": edit-and-execute-command'
 
 # history
 HISTFILE="$XDG_CONFIG_HOME/sh/bash-history"
+HISTSIZE=9999999
+HISTFILESIZE=9999999
 bind '"\e[A": history-search-backward'
 bind '"\e[B": history-search-forward'
 
@@ -35,27 +38,27 @@ bind '"\e[B": history-search-forward'
 
 # readable colours when using the tty, which doesn't have annaisms
 [[ "$TERM" = linux ]] &&
-	accent=$'\033[34m'      accent2=$'\033[31m' ||
-	accent=$'\033[38;5;16m' accent2=$'\033[38;5;17m'
+	bash_shell_accent=$'\033[34m'      bash_shell_accent2=$'\033[31m' ||
+	bash_shell_accent=$'\033[38;5;16m' bash_shell_accent2=$'\033[38;5;17m'
 
 # cute sudo
 export SUDO_PROMPT=$'pass for\033[38;05;16m %u\033[0m '
 
 # cute cnf
 command_not_found_handle() {
-	printf 'not found: %s%s\033[0m\n' "$accent" "$1" >&2
+	printf 'not found: %s%s\033[0m\n' "$bash_shell_accent" "$1" >&2
 	return 127
 }
 
 # main prompt
-PS1='\[\033[0m\]\[$col\] > \[\033[0m\]'
+PS1='\[\033[0m\]\[$bash_shell_col\] > \[\033[0m\]'
 PROMPT_COMMAND=_prompt
 
 _prompt() {
 	## exit status
 	case $? in
-		0) col=$accent;;
-		*) col=$accent2
+		0) bash_shell_col=$bash_shell_accent;;
+		*) bash_shell_col=$bash_shell_accent2
 	esac
 
 	## git
@@ -63,7 +66,7 @@ _prompt() {
 	timeout 0.04 git rev-parse &>/dev/null && {
 		out=$(git status --porcelain)
 		git='*'
-		[[ "$out" =~ .*^.[M].* ]] && git=$'\e[37m*'
+		[[ "$out" =~ .*^.[MD].* ]] && git=$'\e[37m*'
 		[[ "$out" =~ .*^[MA].* ]] && git=$'\e[38;5;16m*'
 	}
 
